### PR TITLE
Fix for Extension Folder location

### LINKED ISSUE #1: Extension folder hard coded
Currently the logic to find the extension path is hardcoded to look in `$HOMEDIR/.azuredatastudio/extensions`. But this isn't correct in all cases - for example : 

- Dev running out of sources
- Insiders/RC1/other quality
- Anyone using a custom extension folder (`--extensions-dir` command line arg)

Given that the only reason this logic seems to exist is to find the location of the extension - it would be far better to just use [`ExtensionContext.extensionPath`](https://github.com/microsoft/azuredatastudio/blob/main/src/vs/vscode.d.ts#L5842) to get the path to find the Notebooks in.

### PR DESCRIPTION
**Pull request by VasuBhog**
This PR fixes #1. 
It uses the proper extension location instead of the hardcoded homedir.

### CODE REVIEW

File: src/notebook.ts [hunk 1]
```diff
@@ -6,49 +6,20 @@ import * as path from 'path';
...
-    let folderExt = path.basename(folderName).toLowerCase();
-
-    if (folderExt.indexOf(('vasubhog.dot-net-interactive-kernels').toLowerCase()) > -1) {
-        let fullFolderPath = path.join(rootExtensionsFolder, folderName, 'content');
-        try {
-            extractNotebooksFromFolder(fullFolderPath, notebookNames);
-        } catch (e) {
-            vscode.window.showErrorMessage("Unable to access " + fullFolderPath + ": " + e.message);
-        }
+// This function looks in the user's extensions folder for notebooks to be opened.
```
Comment (Charles-Gagnon) [inline src/notebook.ts]: I'd suggest updating this to indicate that it looks specifically in the folder for this extension

File: src/notebook.ts [hunk 2]
```diff
@@ -6,49 +6,20 @@ import * as path from 'path';
...
+// If it encounters an error, a message will appear in an error window.
+const processNotebooks = (context: vscode.ExtensionContext) => {
+    let notebook = context.extensionPath + '/content/Install-Dot-Net-Kernels.ipynb';
```
Comment (Charles-Gagnon) [inline src/notebook.ts]: Use path.join

File: src/notebook.ts [hunk 3]
```diff
@@ -6,49 +6,20 @@ import * as path from 'path';
...
+    try {
+        let notebookNames: Array<string> = [];
```
Comment (Charles-Gagnon) [inline src/notebook.ts]: Given that you aren't actually trying to open the file anymore this can't really fail so the try/catch seems unnecessary. I'd suggest just simplifying this to create the notebook path directly in activate and call showNotebookDocument on that.

**Review by Charles-Gagnon — APPROVED** [review]
Some cleanup could be done but this at least fixes the issue
